FROM alpine:latest

RUN apk --no-cache add nginx nodejs tini nodejs-npm

COPY devops/nginx.conf /etc/nginx/nginx.conf
WORKDIR /opt/client

COPY client/package.json .
RUN npm install
COPY client/ .
COPY devops/run.sh .

EXPOSE 80

CMD ["/sbin/tini", "--", "/opt/client/run.sh"]
