module.exports = [
    'https://0kdovoz7zi.execute-api.us-east-2.amazonaws.com/prod',
    'https://pcttkxyzf0.execute-api.us-east-1.amazonaws.com/prod',
    'https://6w8f5e55a4.execute-api.us-west-1.amazonaws.com/prod',
    'https://jv0clmnxg5.execute-api.us-west-2.amazonaws.com/prod',
    'https://93bvwmqd79.execute-api.ap-south-1.amazonaws.com/prod',
    'https://fwhalnd0tg.execute-api.ap-northeast-2.amazonaws.com/prod',
    'https://90acj4ic73.execute-api.ap-southeast-1.amazonaws.com/prod',
    'https://md4l1llvpi.execute-api.ap-southeast-2.amazonaws.com/prod',
    'https://3dkp1evs5k.execute-api.ap-northeast-1.amazonaws.com/prod',
    'https://ebagqoyyjl.execute-api.ca-central-1.amazonaws.com/prod',
    'https://1vk3u1qidi.execute-api.eu-central-1.amazonaws.com/prod',
    'https://brcfquc82m.execute-api.eu-west-1.amazonaws.com/prod',
    'https://3kay0aqmhd.execute-api.eu-west-2.amazonaws.com/prod',
    'https://qivkjag4ak.execute-api.eu-west-3.amazonaws.com/prod',
    'https://68kervu5lf.execute-api.sa-east-1.amazonaws.com/prod',
]
