FROM alpine:latest

RUN apk --no-cache add nginx nodejs tini nodejs-npm

COPY devops/nginx.conf /etc/nginx/nginx.conf
WORKDIR /opt/client

COPY package.json .
COPY prod.config.js config.js
RUN npm install
COPY . .
COPY devops/run.sh .

EXPOSE 80

CMD ["/sbin/tini", "--", "/opt/client/run.sh"]
